/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasikasir_ujikomz;

/**
 *
 * @author rps
 */
public class FromProduk extends javax.swing.JFrame {

    /**
     * Creates new form FromProduk
     */
    public FromProduk() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIDProduk = new java.awt.TextField();
        txtProduk = new java.awt.TextField();
        txtHarga = new java.awt.TextField();
        txtStok = new java.awt.TextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("INPUT PRODUK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(212, 212, 212))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 644, 116);

        jLabel2.setText("ID Produk");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(27, 165, 52, 16);

        jLabel3.setText("Nama Produk");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 208, 73, 16);

        jLabel4.setText("Harga");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(47, 255, 32, 16);

        jLabel5.setText("Stok");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(56, 307, 23, 16);
        getContentPane().add(txtIDProduk);
        txtIDProduk.setBounds(122, 161, 136, 20);

        txtProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdukActionPerformed(evt);
            }
        });
        getContentPane().add(txtProduk);
        txtProduk.setBounds(122, 208, 136, 20);
        getContentPane().add(txtHarga);
        txtHarga.setBounds(122, 255, 136, 20);
        getContentPane().add(txtStok);
        txtStok.setBounds(122, 307, 136, 20);

        btnSimpan.setIcon(new javax.swing.ImageIcon("C:\\Users\\rps\\Downloads\\icons8-save-35.png")); // NOI18N
        btnSimpan.setText("SIMPAN");
        getContentPane().add(btnSimpan);
        btnSimpan.setBounds(47, 387, 113, 42);

        btnEdit.setIcon(new javax.swing.ImageIcon("C:\\Users\\rps\\Downloads\\icons8-edit-30 (1).png")); // NOI18N
        btnEdit.setText("EDIT");
        getContentPane().add(btnEdit);
        btnEdit.setBounds(201, 389, 87, 37);

        btnHapus.setIcon(new javax.swing.ImageIcon("C:\\Users\\rps\\Downloads\\icons8-delete-26.png")); // NOI18N
        btnHapus.setText("HAPUS");
        getContentPane().add(btnHapus);
        btnHapus.setBounds(314, 391, 98, 33);

        btnKeluar.setIcon(new javax.swing.ImageIcon("C:\\Users\\rps\\Downloads\\icons8-exit-24.png")); // NOI18N
        btnKeluar.setText("KELUAR");
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(451, 392, 100, 31);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 161, 307, 149);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.TextField txtHarga;
    private java.awt.TextField txtIDProduk;
    private java.awt.TextField txtProduk;
    private java.awt.TextField txtStok;
    // End of variables declaration//GEN-END:variables
}
