/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasikasir_ujikomz;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author rps
 */
public class FromPelanggan extends javax.swing.JFrame {
Connection konek;
PreparedStatement pst;
ResultSet rst;
    /**
     * Creates new form FromPelanggan
     */
    public FromPelanggan() {
        initComponents();
        konek = Koneksi.koneksiDB();
        mulai();
        tampilwaktu();
        updateTabel();
    }
public void mulai() {
    txtJam.setEnabled(false);
    txtTanggal.setEnabled(false);
}
public void tampilWaktu() {
    Thread clock = new Thread(){
        public void run(){
            for(;;){
                Calendar cal = Calendar.getInstance();
                SimpleDateFormat jam = new SimpleDateFormat("hh:mm:ss");
                SimpleDateFormat tanggal= new SimpleDateFormat("dd:mm:yy");
                txtJam.setText.(jam.format(cal.getTime()));
                txtTanggal.setText(tanggal.format(cal.getTime()));
                
            }
        }
    };
    clock.start();
}
public void updateTabel(){
    try{
        String sql = "select * from pelanggan";
        pst = konek.prepareStatement(sql);
        rst = pst.executeQuery();
        tblPelanggan.setModel(DbUtils.resultSetToTableModel(rst));
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
}
public void clear(){
    txtId.setText("");
    txtNama.setText("");
    txtAlamat.setText("");
    txtNo.setText("");
}
public void simpan(){
    try{
        String sql = "insert into pelanggan (PelangganID,NamaPelanggan,Aalamat,NomerTelepon) value (?,?,?,?)";
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtJam = new java.awt.TextField();
        txtTanggal = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new java.awt.TextField();
        txtNama = new java.awt.TextField();
        txtNo = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPelanggan = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("INPUT PELANGGAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(307, 307, 307))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 940, 116);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ID Pelanggan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(27, 151, 80, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nama Pelanggan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 198, 100, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(47, 248, 50, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("No Telepon");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 370, 64, 16);
        getContentPane().add(txtId);
        txtId.setBounds(121, 151, 135, 20);
        getContentPane().add(txtNama);
        txtNama.setBounds(121, 194, 135, 20);
        getContentPane().add(txtNo);
        txtNo.setBounds(130, 370, 135, 20);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(121, 248, 210, 74);

        btnSimpan.setIcon(new javax.swing.ImageIcon("C:\\Users\\rps\\Downloads\\icons8-save-35.png")); // NOI18N
        btnSimpan.setText("SIMPAN");
        getContentPane().add(btnSimpan);
        btnSimpan.setBounds(58, 456, 113, 42);

        btnEdit.setIcon(new javax.swing.ImageIcon("C:\\Users\\rps\\Downloads\\icons8-edit-30 (1).png")); // NOI18N
        btnEdit.setText("EDIT");
        getContentPane().add(btnEdit);
        btnEdit.setBounds(202, 458, 87, 37);

        btnHapus.setIcon(new javax.swing.ImageIcon("C:\\Users\\rps\\Downloads\\icons8-delete-26.png")); // NOI18N
        btnHapus.setText("HAPUS");
        getContentPane().add(btnHapus);
        btnHapus.setBounds(307, 460, 98, 33);

        btnKeluar.setIcon(new javax.swing.ImageIcon("C:\\Users\\rps\\Downloads\\icons8-exit-24.png")); // NOI18N
        btnKeluar.setText("KELUAR");
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(435, 461, 100, 31);

        tblPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPelanggan);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(420, 180, 310, 200);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\rps\\Downloads\\meli.jpg")); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-190, 110, 1810, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPelanggan;
    private javax.swing.JTextArea txtAlamat;
    private java.awt.TextField txtId;
    private java.awt.TextField txtJam;
    private java.awt.TextField txtNama;
    private java.awt.TextField txtNo;
    private java.awt.TextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
